### ISSUE TITLE
Move towards the LLM OpenTelemetry convention

### ISSUE THREAD

**Issue by zzn2** [microsoft/promptflow#2266]
OpenLLMetry is working with OpenTelemetry on defining new LLM semantic conventions:
https://github.com/open-telemetry/semantic-conventions/pull/639
And we are going to align with the new convention for the long-term plan: #2162 

We should move towards the new convention gradually.
As the first step, we can rename the following attributes in the LLM span to align with the new convention:

For "LLM" spans:
| Rename from | Rename to |
|:--- |:--- |
| llm.token_count.prompt | llm.usage.prompt_tokens |
| llm.token_count.completion | llm.usage.completion_tokens |
| llm.token_count.total | llm.usage.total_tokens |
| llm.model | llm.response.model |

For "Embedding" spans:
| Rename from | Rename to |
|:--- |:--- |
| embedding.token_count.prompt | llm.usage.prompt_tokens |
| embedding.token_count.total | llm.usage.total_tokens |
| embedding.model | llm.response.model |

```[tasklist]
### Tasks
- [x] Rename span attributes in promptflow.tracing package
- [x] TraceUI reads data from the new attribute name
- [x] Update sample data and TraceUI demo site
```
